using UnityEngine;

public class CharacterAnimationController : MonoBehaviour
{
    private Animator animator;

    private void Start()
    {
      
        animator = GetComponent<Animator>();
    }

    private void Update()
    {

        if (Input.GetKey(KeyCode.W) || Input.GetKey(KeyCode.A) || Input.GetKey(KeyCode.S) || Input.GetKey(KeyCode.D))
        {
            if (Input.GetKey(KeyCode.LeftShift) && Input.GetKey(KeyCode.W))
            {
                animator.SetBool("Sprinting", true);       
                animator.SetBool("Walking", false);        
            }
            else
            {
                animator.SetBool("Walking", true);         
                animator.SetBool("Sprinting", false);     
            }
        }
        else
        {
            animator.SetBool("Walking", false);           
            animator.SetBool("Sprinting", false);         
        }

 
        if (Input.GetKeyDown(KeyCode.Space))
        {
            animator.SetTrigger("Jumping");               
        }

     
        if (Input.GetKey(KeyCode.W) && Input.GetKey(KeyCode.LeftControl))
        {
            animator.SetBool("Crouching", true);          
            animator.SetBool("Walking", false); 
        }
        else
        {
            animator.SetBool("Crouching", false);         
        }
    }
}
